### ISSUE TITLE
Guide for sparkler and hdfs

### ISSUE THREAD

**Issue by MuhammadTalhaAfzal** [USCDataScience/sparkler#25]
In the guide there is nothing  on how to connect hdfs with sparkler. In notes for Apache Nutch Users and developers.

Note 2: Crawled content
    Sparkler can produce the segments on HDFS, trying to keep it compatible with nutch content format.

Please share the steps. How?

**Comment by karanjeets** [comment]
@MuhammadTalhaAfzal: 

The capability already exists in Sparkler. If you see [Crawler.scala Line-174](https://github.com/USCDataScience/sparkler/blob/master/sparkler-app/src/main/scala/edu/usc/irds/sparkler/pipeline/Crawler.scala#L174), we are saving the crawled content on HDFS in Nutch format.

Hope it answers your question.

**Comment by MuhammadTalhaAfzal** [comment]
@karanjeets:

I have hadoop 2.5.2, already installed. So in order to store content in hdfs i am using this command when crawling.
`java -jar sparkler-app-0.1.jar crawl -id sparkler-job-xxxxxxxx -o hdfs://localhost:9000/sparklercontent`

but i am getting this error -> No FileSystem for schema: hdfs

Q: Is there any configuration file of sparkler i have to update in order to use hdfs like define path and version?
Q: Is sparkler compatible with all hadoop versions?

Sorry, but i am really confused right now.

**Comment by karanjeets** [comment]
@MuhammadTalhaAfzal: Sparkler currently picks up hadoop from Spark library which uses Hadoop 2.2.0. Now if hadoop 2.5.2 has the backward compatibility to hadoop 2.2.0, it should work fine.

**Quick Tip**
I see a lot of places you are using java. Instead of this, you should run this as a spark job (using spark-submit) and make sure it is aware of HDFS. I am quite sure that this will solve your problem. 

I am preparing a step by step guide for running Sparkler on HDFS.  I am on travel this week and it might get a little late.

@thammegowda: In case you have time this week, see what is going wrong here.

**Comment by thammegowda** [comment]
@MuhammadTalhaAfzal 
Looks like you are running in local mode. What's your spark master URL? Is it `local[*]` ?

By default Spark saves its output to the file system it is aware of.
if you are running in local mode, it uses local file system
if you have spark running over YARN with HDFS, then it will use HDFS. In this case, you either submit job using `spark-submit` OR set master url properly.

If you are not sure what file system it is using, try using relative paths for output and see where it stores.

**Comment by thammegowda** [comment]
Refer to deployment with juju wiki (Work-in-progress)  https://github.com/USCDataScience/sparkler/wiki/Deploying-Sparkler-with-Juju
