### ISSUE TITLE
Is the default config overrideable without updating the jar?

### ISSUE THREAD

**Issue by buggtb** [USCDataScience/sparkler#53]
I don't know if I'm just missing something or its not done yet, can I define an external site-default.yaml type config file?

**Comment by thammegowda** [comment]
Yes!
You can prefix your file to the classpath to override it without updating the jar.

I use `bin/sparkler.sh` script; it prefixes the resources in `./resources/` directory to classpath.
`java -cp $DIR/resources:$JAR edu.usc.irds.sparkler.Main $@`

Currently, we place such files in `conf` directory, all changes made here are tracked in git.
Maven will make a copy of it to `resources` directory. Here you can modify it at runtime. if you dont need these changes to be pushed to repo you can safely ignore it (otherwise, please copy the changes to conf to checkin!)

Please close this issue if it solved, or if you have suggestions I would like to listen :-)

**Comment by buggtb** [comment]
Cool. Personally I think it would be much more convenient to have a --config-dir type flag on the command line or something but this will do for me! (maybe add it to a wiki page somewhere)
