### ISSUE TITLE
crawling all links of same domain in Sparkler - best practice

### ISSUE THREAD

**Issue by rainergeissendoerfer** [USCDataScience/sparkler#87]
What would be the recommended approach to exclude outgoing links (to other domains) for subsequent crawls in Sparkler by default?

**Comment by thammegowda** [comment]
@rainergeissendoerfer 

If your list of domains is small, you may configure `urlfiter-regex` plugin.  More on this (https://wiki.apache.org/nutch/NutchTutorial#A.28Optional.29_Configure_Regular_Expression_Filters)

If you have more domains and wouldn't like to write rules for all the domains (perhaps it is inefficient too), then we need to develop a plugin and add it to sparkler.

Sparkler provides a `URLFilter` contract which has

```java
boolean filter(String url, String parent) {...}
```
You may consider https://github.com/USCDataScience/sparkler/tree/master/sparkler-plugins/urlfilter-regex as an example and implement a new plugin to fit your needs. I assume this plugin will be simpler than the regex filter since you just need to add one liner
```java
return new Url(url).getHost().equals(new URL(parent).getHost());
```


P.S. I created #88 for discussion of plugin. We will be very happy to have you as a contributor :-)

**Comment by thammegowda** [comment]
Closing this issue, Use #88 page for the further discussion on this feature
